### ISSUE TITLE
Auto-completion does not work for entities

### ISSUE THREAD

**Issue by anybody84** [hassio-addons/addon-vscode#148]
# Problem/Motivation

> Auto-completion does not work for entities. When pressing Ctrl+Space `Loading...` window/pop-up appears, but it remains in this state and the list of entities never gets loaded. However, it works for icons.

## Expected behavior

> The list of entities should be loaded, so I can select the one which I want to use.

## Actual behavior

> The list is not loaded. I already checked addon logs - nothing suspicious there. I also reinstalled the addon, but it didn't help. Is there anything else I can do to debug it?

![image](https://user-images.githubusercontent.com/37036776/102009954-25b64880-3d3b-11eb-9909-d73609f72d9c.png)

![image](https://user-images.githubusercontent.com/37036776/102010087-ffdd7380-3d3b-11eb-8c70-3cc30af97948.png)

**Comment by frenck** [comment]
Please provide logs.

**Comment by anybody84** [comment]
Here you are:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.9.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 0.118.5
 Home Assistant Supervisor: 2020.12.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:56:51] INFO: Starting the code server...
[2020-12-13T11:56:52.600Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2020-12-13T11:56:53.391Z] info  code-server 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b
[2020-12-13T11:56:53.394Z] info  Using user-data-dir /data/vscode
[2020-12-13T11:56:53.570Z] info  Using config file ~/.config/code-server/config.yaml
[2020-12-13T11:56:53.571Z] info  HTTP server listening on http://0.0.0.0:1337 
[2020-12-13T11:56:53.572Z] info    - Authentication is disabled 
[2020-12-13T11:56:53.572Z] info    - Not serving HTTPS
```
These are the logs after:
- uninstalling the addon
- restarting HA
- installing the addon
- facing again this issue

**Comment by frenck** [comment]
Extension log from VSCode. The add-on does start, so the add-on logs would not provide information.

**Comment by anybody84** [comment]
Ok, not really sure if these are the logs you're asking for, but anyway - I will attach everything I found.

`Log (Remote Server)`:
```
[2020-12-13 21:31:25.147] [remoteagent] [warning] [File Watcher (chokidar)] Error: Circular symlink detected: "/config/config" points to "/config"
[2020-12-13 21:31:47.506] [remoteagent] [warning] [File Watcher (chokidar)] Error: Circular symlink detected: "/config/config" points to "/config"
[2020-12-14 07:50:55.435] [remoteagent] [warning] [File Watcher (chokidar)] Error: Circular symlink detected: "/config/config" points to "/config"
[2020-12-14 08:12:12.990] [remoteagent] [warning] [File Watcher (chokidar)] Error: Circular symlink detected: "/config/config" points to "/config"
```

`Log (Window)`:
```
Error: Cannot find module './build/Release/watchdog'
Require stack:
- /usr/local/lib/code-server/lib/vscode/node_modules/native-watchdog/index.js
- /usr/local/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/local/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/local/lib/code-server/lib/vscode/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.t._load (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1066:11)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/code-server/lib/vscode/node_modules/native-watchdog/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.t._load (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1066:11)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Function.s [as __$__nodeRequire] (/usr/local/lib/code-server/lib/vscode/out/vs/loader.js:34:963)
    at /usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1068:319
    at l.fire (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
    at v.fire (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
    at /usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1067:494
    at l.fire (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
    at v.fire (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
    at t.PersistentProtocol._receiveMessage (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261:629)
    at /usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258:708
    at l.fire (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
    at p.acceptChunk (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:989)
    at /usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:341
    at l.fire (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
    at v._acceptChunk (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:266:334)
    at /usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:264:479
    at Socket.t (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263:276)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    at Timeout._onTimeout (/usr/local/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:9:510)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

`Log (Worker Extention Host)`:
```
[2020-12-14 08:12:13.295] [exthost.log] [info] extension host started
[2020-12-14 08:12:13.311] [exthost.log] [info] eager extensions activated
```

`Log (Remote Extention Host)`:
```
[2020-12-14 07:50:56.182] [exthost] [info] extension host started
[2020-12-14 07:50:56.221] [exthost] [info] ExtensionService#_doActivateExtension emilast.LogFileHighlighter {"startup":false,"extensionId":{"value":"emilast.LogFileHighlighter","_lower":"emilast.logfilehighlighter"},"activationEvent":"onLanguage:log"}
[2020-12-14 07:50:56.222] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/emilast.LogFileHighlighter-2.10.0/out/src/extension
[2020-12-14 07:50:56.254] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-12-14 07:50:56.254] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/debug-auto-launch/dist/extension
[2020-12-14 07:50:56.263] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-12-14 07:50:56.263] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/emmet/dist/node/emmetNodeMain
[2020-12-14 07:50:56.329] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-12-14 07:50:56.329] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/git/dist/main
[2020-12-14 07:50:56.471] [exthost] [info] ExtensionService#_doActivateExtension lukas-tr.materialdesignicons-intellisense {"startup":true,"extensionId":{"value":"lukas-tr.materialdesignicons-intellisense","_lower":"lukas-tr.materialdesignicons-intellisense"},"activationEvent":"*"}
[2020-12-14 07:50:56.471] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/lukas-tr.materialdesignicons-intellisense-3.1.0/out/extension.js
[2020-12-14 07:50:56.737] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-12-14 07:50:56.737] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/merge-conflict/dist/mergeConflictMain
[2020-12-14 07:50:56.746] [exthost] [info] ExtensionService#_doActivateExtension oderwat.indent-rainbow {"startup":true,"extensionId":{"value":"oderwat.indent-rainbow","_lower":"oderwat.indent-rainbow"},"activationEvent":"*"}
[2020-12-14 07:50:56.746] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/oderwat.indent-rainbow-7.4.0/out/extension
[2020-12-14 07:50:56.749] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-12-14 07:50:56.749] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/search-result/dist/extension.js
[2020-12-14 07:50:57.016] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-12-14 07:50:57.016] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/github/dist/extension.js
[2020-12-14 07:50:57.274] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2020-12-14 07:50:57.274] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/ms-vscode.js-debug/src/extension.js
[2020-12-14 07:50:57.765] [exthost] [info] ExtensionService#_doActivateExtension keesschollaart.vscode-home-assistant {"startup":true,"extensionId":{"value":"keesschollaart.vscode-home-assistant","_lower":"keesschollaart.vscode-home-assistant"},"activationEvent":"workspaceContains:**/configuration.yaml,**/ui-lovelace.yaml"}
[2020-12-14 07:50:57.765] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/keesschollaart.vscode-home-assistant-1.13.0/out/extension
[2020-12-14 07:50:58.103] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2020-12-14 07:50:58.103] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/esbenp.prettier-vscode-5.8.0/dist/extension
[2020-12-14 07:50:58.365] [exthost] [info] ExtensionService#_doActivateExtension usernamehw.errorlens {"startup":false,"extensionId":{"value":"usernamehw.errorlens","_lower":"usernamehw.errorlens"},"activationEvent":"onStartupFinished"}
[2020-12-14 07:50:58.365] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/usernamehw.errorlens-3.2.4/dist/extension
[2020-12-14 07:50:58.374] [exthost] [info] eager extensions activated
[2020-12-14 08:12:13.761] [exthost] [info] extension host started
[2020-12-14 08:12:13.847] [exthost] [info] ExtensionService#_doActivateExtension emilast.LogFileHighlighter {"startup":false,"extensionId":{"value":"emilast.LogFileHighlighter","_lower":"emilast.logfilehighlighter"},"activationEvent":"onLanguage:log"}
[2020-12-14 08:12:13.848] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/emilast.LogFileHighlighter-2.10.0/out/src/extension
[2020-12-14 08:12:13.923] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-12-14 08:12:13.923] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/debug-auto-launch/dist/extension
[2020-12-14 08:12:13.931] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-12-14 08:12:13.931] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/emmet/dist/node/emmetNodeMain
[2020-12-14 08:12:14.001] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-12-14 08:12:14.001] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/git/dist/main
[2020-12-14 08:12:14.126] [exthost] [info] ExtensionService#_doActivateExtension lukas-tr.materialdesignicons-intellisense {"startup":true,"extensionId":{"value":"lukas-tr.materialdesignicons-intellisense","_lower":"lukas-tr.materialdesignicons-intellisense"},"activationEvent":"*"}
[2020-12-14 08:12:14.126] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/lukas-tr.materialdesignicons-intellisense-3.1.0/out/extension.js
[2020-12-14 08:12:14.294] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-12-14 08:12:14.294] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/merge-conflict/dist/mergeConflictMain
[2020-12-14 08:12:14.302] [exthost] [info] ExtensionService#_doActivateExtension oderwat.indent-rainbow {"startup":true,"extensionId":{"value":"oderwat.indent-rainbow","_lower":"oderwat.indent-rainbow"},"activationEvent":"*"}
[2020-12-14 08:12:14.302] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/oderwat.indent-rainbow-7.4.0/out/extension
[2020-12-14 08:12:14.304] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-12-14 08:12:14.305] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/search-result/dist/extension.js
[2020-12-14 08:12:14.538] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-12-14 08:12:14.539] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/github/dist/extension.js
[2020-12-14 08:12:14.729] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2020-12-14 08:12:14.729] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/local/lib/code-server/lib/vscode/extensions/ms-vscode.js-debug/src/extension.js
[2020-12-14 08:12:15.215] [exthost] [info] ExtensionService#_doActivateExtension keesschollaart.vscode-home-assistant {"startup":true,"extensionId":{"value":"keesschollaart.vscode-home-assistant","_lower":"keesschollaart.vscode-home-assistant"},"activationEvent":"workspaceContains:**/configuration.yaml,**/ui-lovelace.yaml"}
[2020-12-14 08:12:15.215] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/keesschollaart.vscode-home-assistant-1.13.0/out/extension
[2020-12-14 08:12:15.508] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2020-12-14 08:12:15.508] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/esbenp.prettier-vscode-5.8.0/dist/extension
[2020-12-14 08:12:15.780] [exthost] [info] ExtensionService#_doActivateExtension usernamehw.errorlens {"startup":false,"extensionId":{"value":"usernamehw.errorlens","_lower":"usernamehw.errorlens"},"activationEvent":"onStartupFinished"}
[2020-12-14 08:12:15.780] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.code-server/extensions/usernamehw.errorlens-3.2.4/dist/extension
[2020-12-14 08:12:15.789] [exthost] [info] eager extensions activated
```

In case this is not what you need, please let me know where to find it.

**Comment by frenck** [comment]
`Error: Circular symlink detected: "/config/config" points to "/config"`

You have a circular symlink in your configuration folder. Basically, you have a never ending configuration because of that. Remove that symlink you have created there.
