### ISSUE TITLE
not starting correctly with yamlint

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-vscode#15]
# Problem/Motivation
i gave it a new try , starting first with no addon , it worked .
then installing with the addons , and i got the logs detailed below .
hope this helps .
thanks .
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior
````
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 mysql-common all 5.8+1.0.4 [7,308 B]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libmysqlclient20 amd64 5.7.25-0ubuntu0.18.04.2 [818 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libdbd-mysql-perl amd64 4.046-1 [82.0 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 libreadline5 amd64 5.2+dfsg-3build1 [99.5 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libterm-readkey-perl amd64 2.37-1build1 [24.4 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 mariadb-common all 1:10.1.38-0ubuntu0.18.04.1 [15.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 mariadb-client-core-10.1 amd64 1:10.1.38-0ubuntu0.18.04.1 [4,763 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 libconfig-inifiles-perl all 2.94-1 [40.4 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libjemalloc1 amd64 3.6.0-11 [82.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 mariadb-client-10.1 amd64 1:10.1.38-0ubuntu0.18.04.1 [5,626 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 mariadb-client all 1:10.1.38-0ubuntu0.18.04.1 [12.8 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 12.3 MB in 8s (1,636 kB/s)
Selecting previously unselected package libaio1:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 13831 files and directories currently installed.)
Preparing to unpack .../00-libaio1_0.3.110-5_amd64.deb ...
Unpacking libaio1:amd64 (0.3.110-5) ...
Selecting previously unselected package libdbi-perl.
Preparing to unpack .../01-libdbi-perl_1.640-1_amd64.deb ...
Unpacking libdbi-perl (1.640-1) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../02-mysql-common_5.8+1.0.4_all.deb ...
Unpacking mysql-common (5.8+1.0.4) ...
Selecting previously unselected package libmysqlclient20:amd64.
Preparing to unpack .../03-libmysqlclient20_5.7.25-0ubuntu0.18.04.2_amd64.deb ...
Unpacking libmysqlclient20:amd64 (5.7.25-0ubuntu0.18.04.2) ...
Selecting previously unselected package libdbd-mysql-perl.
Preparing to unpack .../04-libdbd-mysql-perl_4.046-1_amd64.deb ...
Unpacking libdbd-mysql-perl (4.046-1) ...
Selecting previously unselected package libreadline5:amd64.
Preparing to unpack .../05-libreadline5_5.2+dfsg-3build1_amd64.deb ...
Unpacking libreadline5:amd64 (5.2+dfsg-3build1) ...
Selecting previously unselected package libterm-readkey-perl.
Preparing to unpack .../06-libterm-readkey-perl_2.37-1build1_amd64.deb ...
Unpacking libterm-readkey-perl (2.37-1build1) ...
Selecting previously unselected package mariadb-common.
Preparing to unpack .../07-mariadb-common_1%3a10.1.38-0ubuntu0.18.04.1_all.deb ...
Unpacking mariadb-common (1:10.1.38-0ubuntu0.18.04.1) ...
Selecting previously unselected package mariadb-client-core-10.1.
Preparing to unpack .../08-mariadb-client-core-10.1_1%3a10.1.38-0ubuntu0.18.04.1_amd64.deb ...
Unpacking mariadb-client-core-10.1 (1:10.1.38-0ubuntu0.18.04.1) ...
Selecting previously unselected package libconfig-inifiles-perl.
Preparing to unpack .../09-libconfig-inifiles-perl_2.94-1_all.deb ...
Unpacking libconfig-inifiles-perl (2.94-1) ...
Selecting previously unselected package libjemalloc1.
Preparing to unpack .../10-libjemalloc1_3.6.0-11_amd64.deb ...
Unpacking libjemalloc1 (3.6.0-11) ...
Selecting previously unselected package mariadb-client-10.1.
Preparing to unpack .../11-mariadb-client-10.1_1%3a10.1.38-0ubuntu0.18.04.1_amd64.deb ...
Unpacking mariadb-client-10.1 (1:10.1.38-0ubuntu0.18.04.1) ...
Selecting previously unselected package mariadb-client.
Preparing to unpack .../12-mariadb-client_1%3a10.1.38-0ubuntu0.18.04.1_all.deb ...
Unpacking mariadb-client (1:10.1.38-0ubuntu0.18.04.1) ...
Setting up libconfig-inifiles-perl (2.94-1) ...
Setting up libjemalloc1 (3.6.0-11) ...
Setting up mysql-common (5.8+1.0.4) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Setting up libterm-readkey-perl (2.37-1build1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up libaio1:amd64 (0.3.110-5) ...
Setting up libmysqlclient20:amd64 (5.7.25-0ubuntu0.18.04.2) ...
Setting up libreadline5:amd64 (5.2+dfsg-3build1) ...
Setting up libdbi-perl (1.640-1) ...
Setting up mariadb-common (1:10.1.38-0ubuntu0.18.04.1) ...
update-alternatives: using /etc/mysql/mariadb.cnf to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Setting up mariadb-client-core-10.1 (1:10.1.38-0ubuntu0.18.04.1) ...
Setting up libdbd-mysql-perl (4.046-1) ...
Setting up mariadb-client-10.1 (1:10.1.38-0ubuntu0.18.04.1) ...
Setting up mariadb-client (1:10.1.38-0ubuntu0.18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
[cont-init.d] 80-user-packages.sh: exited 0.
[cont-init.d] 81-user-scripts.sh: executing... 
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pip._internal import main
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/cmdoptions.py", line 14, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
[09:27:51] FATAL: Failed executing init command: pip3 install yamllint
[cont-init.d] 81-user-scripts.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by gnkarn** [comment]
it may be a memory problem, i asigning the VM 2GB, and when open this addon it goes to 90% , and next it hangs the machine  . So reboot  and uninstall is the only cure for now .

**Comment by frenck** [comment]
@gnkarn Sorry I'm lost on what you are doing here. Please share the config you are trying to startup.
Secondly, the question remains the same as in #13  (and I'm unsure why you'd create another issue instead of just continuing on the existing one?):

Why are you trying to install yamllint? Since it is installed already! (pre-built, shipped with the add-on).

**Comment by michaelblight** [comment]
I'm having the same problem. I did the following:

1. Installed the add-on.
2. Turned off SSL in the config.
3. Put a password in the config (it then removes it after you save?).
4. Started the add-on.
5. Checked the logs. It ends with `INFO  Connected to shared process`, no errors apparent.
6. Clicked on "Open Web UI". First time it asked for my HA credentials. Welcome page displayed (no prompt for password saved in config?).
7. Clicked on "configuration.yaml". Pretty much the whole VM seemed to hang, including containers not linked to hassio (eg. Portainer, PiHole). After several unintalls/re-installs, it seemed to work once very slowly, but then selecting another file caused it to hang. I had to power cycle to get it going again.

My config is:
```
{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "packages": [],
  "init_commands": []
}
```
It included "password", but every time I save and return to the screen it is gone.

**Comment by frenck** [comment]
@michaelblight your report is not related at all. Password methods has changed in the last release. Please login using your username password from Home Assistant. The password option on the add-on has been removed.

@gnkarn Are you getting back on my question? Or can this be closed?

**Comment by gnkarn** [comment]
just installing as per the docs,

config : {
    "log_level": "info",
    "ssl": false,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem",
    "packages": [
      "mariadb-client"
    ],
    "init_commands": [
      "pip3 install yamllint"
    ]
}

, as i say , this could be that VSC is taking too much memory  from the Virtual Machine, and resources are not enough  .

You can close this , i will continue to use VSC , from the main computer for now , thanks a ton .

**Comment by frenck** [comment]
That is just an example which as a big note right next to it: DO NOT USE.
you do not need to install yamllint, since it is already installed by default. The example just shows HOW you could use the `init_commands` option.
