### ISSUE TITLE
ms-python fails to install pylint due to pip exeption (No module named 'distutils.cmd')

### ISSUE THREAD

**Issue by dadler** [hassio-addons/addon-vscode#315]
## The Problem

The [ms-python.python](https://github.com/Microsoft/vscode-python) VSCode extension fails to install pylint because pip throws an exception.  This is in vscode HASS add-on v3.6.2 on Raspberry PI 4 (64-bit).

## Expected behavior

I expected the python extension to be able to install pylint.

## Actual behavior

It fails to install pylint with the error "ModuleNotFoundError: No module named 'distutils.cmd' " (see full log in the next section).

## Steps to reproduce

1. Install vscode add-on
2. In vscode go to the Extensions view, search for Python, and install ms-python.
3. Open a python file (*.py)
4. Soon a vscode notification appears in the lower right corner: "Linter pylint is not installed".  Click "Install" in the notification.
5. This appears in vscode's Terminal:

```
. /usr/bin/python -m pip install -U pylint --user

 _    _                                         _     _              _
| |  | |                          /\           (_)   | |            | |
| |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
|  __  |/ _ \| '_ ` _ \ / _ \   / /\ \ / __/ __| / __| __/ _` | '_ \| __|
| |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_
|_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|


Our command line:
$ ha help
➜  /config git:(master) ✗ /usr/bin/python -m pip install -U pylint --user
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/configuration.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir, enum
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```
## Proposed changes

The ms-python extension succeeds installing pylint if I first run this in vscode's terminal:
```
apt-get update
apt install python3-distutils
```
So I think the fix is to include python3-distutils in the docker image.

**Comment by dadler** [comment]
I've just realized this is basically the same as #144.  That was resolved by having the user add the package to their config:
```
packages:
  - python3-distutils
init_commands:
  - pip install pylint
```
This does solve my problem, but it's really hard to discover that this is the solution (I googled for a while).

Since it's fairly common to work on python files with homeassistant (e.g. for use with appdaemon, pyscript, or working on the code of homeassistant itself), I'd recommend building this package into vscode's docker image.

**Comment by frenck** [comment]
This add-on is not aimed at python development. Customizations can be done if wished for.

For it's main purpose there is no reason to distribute packages to everybody while almost no-one needs it.

Therefor, I will not be adding this suggestion. Nevertheless, thanks for thinking along.
