### ISSUE TITLE
Contiously reconnects

### ISSUE THREAD

**Issue by Se7enair** [hassio-addons/addon-vscode#360]
# Problem/Motivation

VSCode is no longer functional. Want to use it.

## Expected behavior

Only connect once when starting and then keep the connection

## Actual behavior

tries to connect continuously

## Steps to reproduce

Start VSCode and wait. A complete reinstall helpef for a few hours. Then the issue came back.  

## Proposed changes

no fix

Version
core-2021.12.4

Version
supervisor-2021.12.2

Betriebssystem
Home Assistant OS 7.0

Addon log

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 3.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.12.4
 Home Assistant Supervisor: 2021.12.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:22:57] INFO: Starting the code server...
[2021-12-23T12:23:00.003Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2021-12-23T12:23:01.858Z] info  code-server 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2
[2021-12-23T12:23:01.862Z] info  Using user-data-dir /data/vscode
[2021-12-23T12:23:01.931Z] info  Using config file ~/.config/code-server/config.yaml
[2021-12-23T12:23:01.932Z] info  HTTP server listening on http://0.0.0.0:1337 
[2021-12-23T12:23:01.933Z] info    - Authentication is disabled 
[2021-12-23T12:23:01.933Z] info    - Not serving HTTPS 
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
TypeError: Cannot read property 'publicLogError2' of undefined
    at w._flushBuffer (/usr/local/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/entry.js:26:465)
    at Timeout._onTimeout (/usr/local/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/entry.js:26:345)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by Se7enair** [comment]
After complete new install and deleting all related data, it seems to work.
