### ISSUE TITLE
VS Code completely broken for a couple months

### ISSUE THREAD

**Issue by dogmatic69** [hassio-addons/addon-vscode#443]
# Problem/Motivation

Not working at all. Constant loading bar in the UI and files are not able to be opened. Can not expand directories. Everything works momentarily for 2-3 seconds after the page loads

## Expected behavior

able to open files and edit them.

## Actual behavior

Constant loading bar in UI along with lots of errors in the logs

```
[23:03:20] INFO: Starting the code server...
[2022-05-01T21:03:22.231Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-05-01T21:03:23.096Z] info  code-server 4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb
[2022-05-01T21:03:23.098Z] info  Using user-data-dir /data/vscode
[2022-05-01T21:03:23.138Z] info  Using config file ~/.config/code-server/config.yaml
[2022-05-01T21:03:23.138Z] info  HTTP server listening on http://0.0.0.0:1337/ 
[2022-05-01T21:03:23.138Z] info    - Authentication is disabled 
[2022-05-01T21:03:23.138Z] info    - Not serving HTTPS 
[23:03:44] Extension host agent started.
[23:03:46] [172.30.32.2][33d70ea0][ManagementConnection] New connection established.
[23:03:47] [172.30.32.2][db9650a7][ExtensionHostConnection] New connection established.
[23:03:47] [172.30.32.2][db9650a7][ExtensionHostConnection] <613> Launched Extension Host Process.
[23:03:47] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:787:11)
    at Socket._write (net.js:799:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at d.write (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:99625)
    at l._write (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:102547)
    at C._writeFn (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:101013)
    at C._processWriteQueue (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:105969)
    at C.writeMessage (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:105670)
    at l.write (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:101848)
    at b._writeNow (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:78:17476)
    at Timeout._onTimeout (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:78:17288)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'write'
}
Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:787:11)
    at Socket._write (net.js:799:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at d.write (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:99625)
    at l._write (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:102547)
    at C._writeFn (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:101013)
    at C._processWriteQueue (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:105969)
    at C.writeMessage (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:105670)
    at l.write (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:146:101848)
    at b._writeNow (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:78:17476)
    at Timeout._onTimeout (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:78:17288)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'write'
}
[23:03:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[23:03:49] [172.30.32.2][33d70ea0][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[23:03:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:03:50] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
...
[23:08:46] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:46] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:46] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:47] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:47] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:47] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:47] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:48] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:49] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:50] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:50] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:50] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:50] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:50] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:50] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:51] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:51] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:51] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:51] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:52] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:52] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:52] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:52] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:52] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:53] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:53] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:53] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:53] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
[23:08:53] [172.30.32.2][33d70ea0][ManagementConnection] The client has reconnected.
```

The UI console has the following errors:

![image](https://user-images.githubusercontent.com/94674/166164777-40ac4e0d-e753-4673-abf4-8294fbd694f0.png)

## Steps to reproduce

none, just broken always.

## Proposed changes

None

**Comment by dogmatic69** [comment]
I've restarted, and upgraded everything multiple times (this has gone on for long).

I've also uninstalled and reinstalled VS code with no change.  


The problem started on my duckdns domain instance and I then started to use the IP instance for editing files. After a few weeks that too broke and it is now a problem regardless of where I try load VS code.

**Comment by dogmatic69** [comment]
https://user-images.githubusercontent.com/94674/166164950-136e00a6-136b-4aac-b844-a7ef90fe7ae6.MOV

**Comment by sinclairpaul** [comment]
Do you use a proxy, is this specific to one browser?

**Comment by dogmatic69** [comment]
All browsers, all devices, pc, laptop, iphone, linux, windows. Seems to be related to the instance. 

It started around 2-3 months ago but getting annoying now as I'm having to edit files in nano with the terminal addon

**Comment by frenck** [comment]
@dogmatic69 You didn't answer the question...

> Do you use a proxy

?

**Comment by dogmatic69** [comment]
Figured from the edit that the questions answer was self evident with the direct IP connection. There is no proxy.

I'm running on HA Blue and this is direct to it's IP 
![image](https://user-images.githubusercontent.com/94674/166222593-9aa79e75-2ebc-42d9-8da6-b1a423d4670d.png)

**Comment by frenck** [comment]
> Figured from the edit that the questions answer was self evident with the direct IP connection. 

No its not, sorry.

**Comment by dogmatic69** [comment]
Messing around with network requests I took the web socket call and used http which loaded the VS code directly not wrapped in HA. This was still broken but one arg was `folder=/config`. I changed that to `folder=/` and it works. Change it back to `/config` and it's broken

😖

**Comment by sinclairpaul** [comment]
Then it sounds like a resource issue, what is in your config folder? Do you have a lot of nested files/folders?

You can change the default path to open:

<https://github.com/hassio-addons/addon-vscode/blob/main/vscode/DOCS.md#option-config_path>

Would suggest changing it to share or something that's empty, to see if the addon opens ok, then see what happens when you manually open the config folder.

**Comment by dogmatic69** [comment]
Would loading `/` make things worse? 🤔

**Comment by sinclairpaul** [comment]
> Would loading / make things worse? 

Probably, as the file watcher will scan all sub folders (including config)

**Comment by dogmatic69** [comment]
But as I said, when I switch to `/` I can then open and edit files normally. No more issues...

**Comment by dogmatic69** [comment]
So tested out a couple of folders and I can open basically anything (including `/`) but if I open `/config` it dies and I then need to manually go to the url with `folder=/<anything-but-config>`

As for the layout, I don't see that it is anything too crazy. Majority of folders are only files besides `www` and `custom_componets`, mostly related to HACS and other installs. Mixed number of levels, nothing too crazy.

As `/` can be opened and works to view files within config from `/` I'm not sure it is something to do with the files in or nesting.

**Comment by frenck** [comment]
Do you have a `/config/config` folder?

**Comment by dogmatic69** [comment]
nope 

![image](https://user-images.githubusercontent.com/94674/166411946-1dda55da-db23-41a1-a5ec-3671829a6223.png)

**Comment by dogmatic69** [comment]
As for the depth, trying to find a good way to show but it seems rather limited. 

total files, total folders, deepest nested folder.

```
➜  / find /config -type f | wc -l
2864
➜  / find /config -type d | wc -l
440
➜  / find /config -type d -printf '%d\n' | sort -rn | head -1
7
```

**Comment by codedmind** [comment]
Having the same issue since last update 
![image](https://user-images.githubusercontent.com/2910047/166672666-37469f45-c27e-45fc-afe2-40fe3c48d280.png)

I'm using behing nxing proxy... but nothing change on that side only the vscode update

**Comment by dogmatic69** [comment]
I have now tried to open every folder under /config independently and works for all. 

As noted it also works for `/` (besides an expected "file watch" error)

I can also "close" the folder, and everything works just fine.

Any idea if there is a cache or something I can reset in the /config folder? Makes no sense why that particular folder does not work

**Comment by dogmatic69** [comment]
I ended up deleting the vs code addin once again and restarted HA a number of times. After a few days I reinstalled it and it's working so far.
