### ISSUE TITLE
Unused Processes - High CPU

### ISSUE THREAD

**Issue by AzonInc** [hassio-addons/addon-vscode#496]
# Problem/Motivation

After opening the Visual Stusio Code Editor multiple times it's spawning a new node process every time, which causes the cpu to go up to 100%.

## Expected behavior

Spawn only a single process and end the process instead of spaning a new one without ending the old one.

## Actual behavior

There will be multiple node processes running but there should only be one single process all the time.
It's normalizing after killing the Processes manually or stopping the addon.

![image](https://user-images.githubusercontent.com/11911587/189507530-07df3ebc-0045-4068-87c9-bcd453bbbe13.png)

The Process of the Extension keesschollaart.vscode-home-assistant-1.30.1 seems to produce that - even tho I don't see any installed extension in the extensions view.

## Steps to reproduce

1. Open Web UI of "Studio Code Server".
2. Wait until it finished loading.
3. Close the Web UI.
4. Repeat and see CPU increasing every time

Logs & CPU stats:
![image](https://user-images.githubusercontent.com/11911587/189507802-5ff2e835-7468-40bc-a38b-3a5740fd2f23.png)

```
[03:24:59] INFO: Starting the code server...
[2022-09-11T01:25:01.698Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-09-11T01:25:03.182Z] info  code-server 4.6.0 6d3f9ca6a6df30a1bfad6f073f6fa33c0e63abdb
[2022-09-11T01:25:03.185Z] info  Using user-data-dir /data/vscode
[2022-09-11T01:25:03.253Z] info  Using config file ~/.config/code-server/config.yaml
[2022-09-11T01:25:03.253Z] info  HTTP server listening on http://0.0.0.0:1337/ 
[2022-09-11T01:25:03.254Z] info    - Authentication is disabled 
[2022-09-11T01:25:03.254Z] info    - Not serving HTTPS 
[03:25:14] Extension host agent started.
[03:25:16] [172.30.32.2][c7dbd396][ManagementConnection] New connection established.
[03:25:17] [172.30.32.2][cf68eb21][ExtensionHostConnection] New connection established.
[03:25:17] [172.30.32.2][cf68eb21][ExtensionHostConnection] <376> Launched Extension Host Process.
[03:25:25] [File Watcher (parcel)] Unexpected error: No such file or directory (EUNKNOWN) (path: /)
[03:25:25] [File Watcher (universal)] restarting watcher after error: No such file or directory
[03:25:28] [172.30.32.2][c7dbd396][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[03:25:29] [172.30.32.2][cf68eb21][ExtensionHostConnection] <376> Extension Host Process exited with code: 0, signal: null.
[03:26:11] [172.30.32.2][e809cb13][ManagementConnection] New connection established.
[03:26:13] [172.30.32.2][4d508233][ExtensionHostConnection] New connection established.
[03:26:13] [172.30.32.2][4d508233][ExtensionHostConnection] <453> Launched Extension Host Process.
[03:26:23] [172.30.32.2][e809cb13][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[03:26:25] [172.30.32.2][4d508233][ExtensionHostConnection] <453> Extension Host Process exited with code: 0, signal: null.
[03:27:05] [172.30.32.2][dbe66d3c][ManagementConnection] New connection established.
[03:27:06] [172.30.32.2][b7c759ba][ExtensionHostConnection] New connection established.
[03:27:06] [172.30.32.2][b7c759ba][ExtensionHostConnection] <515> Launched Extension Host Process.
[03:27:12] [172.30.32.2][dbe66d3c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[03:27:12] [172.30.32.2][b7c759ba][ExtensionHostConnection] <515> Extension Host Process exited with code: 0, signal: null.
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/local/lib/code-server/lib/vscode/out/bootstrap.js:1:407)
    at process.emit (node:events:402:35)
[03:27:12] Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:148:7922)
    at process.emit (node:events:402:35)
[03:27:33] [172.30.32.2][f987f331][ManagementConnection] New connection established.
[03:27:35] [172.30.32.2][6ba0e108][ExtensionHostConnection] New connection established.
[03:27:35] [172.30.32.2][6ba0e108][ExtensionHostConnection] <546> Launched Extension Host Process.
[03:27:41] [File Watcher (parcel)] Unexpected error: No such file or directory (EUNKNOWN) (path: /)
[03:27:41] [File Watcher (universal)] restarting watcher after error: No such file or directory
[03:27:45] [File Watcher (parcel)] Unexpected error: No such file or directory (EUNKNOWN) (path: /)
[03:27:45] [File Watcher (universal)] restarting watcher after error: No such file or directory
[03:27:56] [172.30.32.2][f987f331][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[03:27:56] [172.30.32.2][6ba0e108][ExtensionHostConnection] <546> Extension Host Process exited with code: 0, signal: null.
[03:28:21] [172.30.32.2][9d2cdb34][ManagementConnection] New connection established.
[03:28:22] [172.30.32.2][9b7bf0d6][ExtensionHostConnection] New connection established.
[03:28:23] [172.30.32.2][9b7bf0d6][ExtensionHostConnection] <655> Launched Extension Host Process.
[03:28:37] [172.30.32.2][9d2cdb34][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[03:28:37] [172.30.32.2][9b7bf0d6][ExtensionHostConnection] <655> Extension Host Process exited with code: 0, signal: null.
```
![image](https://user-images.githubusercontent.com/11911587/189507854-cb374f1d-e56d-418e-9e27-ec6cfbd0cf20.png)

**Comment by andbez** [comment]
Same here on MacOS (12.6).

**Comment by sultanhq** [comment]
Same on RPi4

**Comment by bikeymouse** [comment]
Same here. Took me a while to find out why after a while the CPU was increasing to 60 - 90% (normally 1-2%), which could only be solved by a complete system restart. Disabling this add-on solved it.
Running HASS on a Proxmox virtual machine on a Intel NUC.

**Comment by bikeymouse** [comment]
I tried with  version: 5.4. with includes #525 but that did not solve the issue. Behaviour is still exactly the same.

**Comment by frenck** [comment]
@bikeymouse have you reset your vscode settings as per release notes of 5.4.1? And could you share your add-on configuration?

**Comment by bikeymouse** [comment]
Yes I did the reset in the Terminal.
My configuration is simple ;-)
```
init_commands: []
packages: []

```

**Comment by bikeymouse** [comment]
Update: I just had an epiphany and uninstalled de Add On. 
Now after reinstalling everything works fine!
So problem solved, thanks for your response!
