### ISSUE TITLE
Slow start, and errors in log.

### ISSUE THREAD

**Issue by Korte68** [hassio-addons/addon-vscode#667]
# Problem/Motivation

Very slow starting 

## Expected behavior

Start faster without errors
## Actual behavior

Start slowly, with errors in log

## Steps to reproduce

Start VScode

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

HA running on a synology NAS virtual machine. Latest HA, and latest VScode (5.8)

[19:53:31] [172.30.32.2][ae7ce84e][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[19:53:31] [172.30.32.2][6a7e5c87][ExtensionHostConnection] <577> Extension Host Process exited with code: 0, signal: null.
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda_bg.wasm
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda.js
[19:54:53] [172.30.32.2][01fdb251][ManagementConnection] New connection established.
[19:54:56] [172.30.32.2][5da4c4a5][ExtensionHostConnection] New connection established.
[19:54:56] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed Error: Unable to resolve your shell environment in a reasonable time. Please review your shell configuration and restart.
    at Timeout.<anonymous> (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:96:2557)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[19:54:56] [172.30.32.2][5da4c4a5][ExtensionHostConnection] <748> Launched Extension Host Process.
[19:54:57] ptyHost was unable to resolve shell environment Error: Unable to resolve your shell environment in a reasonable time. Please review your shell configuration and restart.
    at Timeout.<anonymous> (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:96:2557)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by bcutter** [comment]
Better follow / have a look at https://github.com/hassio-addons/addon-vscode/issues/666, the addon seems to have a general issue currently and you might see symptoms of that too.
