### ISSUE TITLE
VS Code fails to start

### ISSUE THREAD

**Issue by bretterer** [hassio-addons/addon-vscode#86]
# Problem/Motivation

Unable to start VS Code add-on.  HASS claims it starts, but when you get to the sidebar and click on the extension it says its not started.  see details below in Actual behavior

## Expected behavior

Start VS Code without issue

## Actual behavior

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.1.0
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: null  (amd64 / qemux86-64)
 Home Assistant Core: 0.107.7
 Home Assistant Supervisor: 214
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[15:50:59] ERROR: Got unexpected response from the API: Service not enabled
[15:50:59] INFO: The above error can be ignored if you don't have MariaDB installed
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:51:03] INFO: Starting the code server...
buffer.js:585
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

RangeError: Index out of range
    at Object.slice (buffer.js:585:37)
    at Buffer.toString (buffer.js:782:14)
    at Object.exports.readString (nbin.js:21:52)
    at Object.7.../common/buffer (nbin.js:785:24)
    at o (nbin.js:1:629)
    at r (nbin.js:1:795)
    at nbin.js:1:824
    at nbin.js:1:88
    at nbin.js:1:320
    at NativeModule.compile (internal/bootstrap/loaders.js:285:5) {
  code: 'ERR_OUT_OF_RANGE'
}
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

## Steps to reproduce

New install of hass.io on an ubuntu server VM from ProxMox
Installed add-ons:
 - Google Assistant SDK
 - Mosquitto broker
 - Node-RED
 - VS Code

after installing vs code, start add-on
go to log and see the above error

## Proposed changes

No idea on a fix here.  I have no experience working with the embedded version of VS Code

## Version Info
HASS: 0.107.7
VS Code Add-on: 2.1.0

**Comment by XtremeOwnageDotCom** [comment]
Steps to reproduce.

Update home assistant to 0.108.0.

Add-on no longer functions. No logs produced, that I have found.

**Comment by XtremeOwnageDotCom** [comment]
I was able to reproduce this issue by taking these exact steps.

Hassio always fails to update, so, I usually take a backup, put the new image into place, and restore the backup.

During the restore, it did reimport vscode- however, the docker container for vscode was missing when running docker container list.

By uninstalling / reinstalling the addon via the UI, corrected the issue.

**Comment by bretterer** [comment]
Pretty sure this is the same issue.  It seems to be most add-ons since version 107

**Comment by bretterer** [comment]
Still getting this issue with the new update 
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.2.0
 You are running the latest version of this add-on.
 System: HassOS 3.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.108.6
 Home Assistant Supervisor: 217
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:44:12] INFO: Starting the code server...
buffer.js:585
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^
RangeError: Index out of range
    at Object.slice (buffer.js:585:37)
    at Buffer.toString (buffer.js:782:14)
    at Object.readFileSync (fs.js:386:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:22)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ERR_OUT_OF_RANGE'
}
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by frenck** [comment]
Please try this with 2.3.0, which just got released.

**Comment by bretterer** [comment]
> Please try this with 2.3.0, which just got released.

Will attempt in the next few days

**Comment by bretterer** [comment]
It appears that this is still an issue with a new install of HA on Proxmox.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.3.0
 You are running the latest version of this add-on.
 System: HassOS 4.9  (amd64 / qemux86-64)
 Home Assistant Core: 0.110.4
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:12:33] INFO: Starting the code server...
buffer.js:607
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^
RangeError: Index out of range
    at Object.slice (buffer.js:607:37)
    at Buffer.toString (buffer.js:804:14)
    at Object.readFileSync (fs.js:408:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1219:22)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_OUT_OF_RANGE'
}
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by CarlKnox** [comment]
Same issue.
Hass.io on Synology 0.112.2
VSC add-on 2.3.0
No add-on logs, Portainer displays Unable to access log folder.

**Comment by frenck** [comment]
@CarlKnox Hass.io doesn't exists. As you running Home Assistant OS or Home Assistant Supervised?

**Comment by MikeTannenbaum** [comment]
following. has anyone had progress getting VS Code to work with OS or Supervised?

**Comment by sprynm** [comment]
Nope: 
![image](https://user-images.githubusercontent.com/4483296/91934378-189baf00-eca0-11ea-9125-dd5a857e9269.png)


- arch | armv7l
- chassis | embedded
- dev | false
- docker | true
- docker_version | 19.03.11
- hassio | true
- host_os | HassOS 4.12
- installation_type | Home Assistant OS
- os_name | Linux
- os_version | 4.19.127-v7l
- python_version | 3.8.3
- supervisor | 235
- timezone | America/Vancouver
- version | 0.114.4
- virtualenv | false

**Comment by CarlKnox** [comment]
I got VS Code to work with supervised. Don’t recall what I changed, however, I’m going away from supervised until it’s more stable. I’ll see if it still works with OS.

**Comment by frenck** [comment]
@CarlKnox There is no different in supervised or OS from an add-on perspective. This add-on is developed on Supervised.

**Comment by sprynm** [comment]
> This add-on is developed on Supervised.

So I assume that's why it's not or me available now?  It odd as I had VS Code running before I had to reimage and restore due to SD card failure.

**Comment by frenck** [comment]
> So I assume that's why it's not available for me now? It's odd as I had VS Code running before I had to reimage and restore due to SD card failure.

No, that is because you are running are 32 bits system or 32 bits operating system. As per documentation of this add-on, it requires 64 bits.
