### ISSUE TITLE
Studio Code Server 5.16.3 stopped functioning after upgrading to Home Assistant 2024.10.1

### ISSUE THREAD

**Issue by chriselera** [hassio-addons/addon-vscode#879]
# Problem/Motivation

> I've been using Studio Code Server to edit my HA configuration files for a while now. I would like to keep continue using it.

## Expected behavior

> When I click on "Studio Code Server" from the HA sidebar, I expect the usual VS Code IDE to open (file explorer on the left and opened files on the right arranged in tabs).

## Actual behavior

> Nothing happens - only black screen on the right. I see error entries in the logs, as follows:

`-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.17.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.10.1
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[09:34:33] INFO: Configuring timezone (Asia/Manila)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
[09:34:33] INFO: Starting code-server...
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2024-10-05T01:34:34.140Z] info  Wrote default config file to /root/.config/code-server/config.yaml
[2024-10-05T01:34:34.458Z] info  code-server 4.93.1 69df01185ce2f80e99c9e4f8c8de1907cc7a9bc5
[2024-10-05T01:34:34.460Z] info  Using user-data-dir /data/vscode
[2024-10-05T01:34:34.476Z] info  Using config file /root/.config/code-server/config.yaml
[2024-10-05T01:34:34.476Z] info  HTTP server listening on http://0.0.0.0:1337/
[2024-10-05T01:34:34.476Z] info    - Authentication is disabled
[2024-10-05T01:34:34.476Z] info    - Not serving HTTPS
[2024-10-05T01:34:34.476Z] info  Session server listening on /data/vscode/code-server-ipc.sock
[09:35:30] 

[09:35:30] Extension host agent started.
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/browser/browser.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/browser/window.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/buffer.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/event.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/lifecycle.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/marshalling.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/path.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/resources.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/network.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/strings.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/platform/product/common/product.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/uri.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/platform/window/common/window.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js`

## Steps to reproduce

> Upgrade Home Assistant Core to 2024.10.1.

## Proposed changes

> N/A. **Upgraded Studio Code Server to 5.17.0 and still the same error.**

**Comment by frenck** [comment]
I'm not able to reproduce this on any of my test setups.

Try upgrading to the latest fresh build.

**Comment by chriselera** [comment]
I did try 5.17.0 earlier and it wasn't working as well. Just installed 5.17.1 and it's working now. Thank you!

Posting logs -- first part is for 5.17.0; last part is 5.17.1 where error was resolved.

`[09:45:15] [172.30.32.2][c337646a][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/local/lib/code-server/lib/vscode/out/server-main.js:1:437)
    at process.emit (node:events:531:35)
[09:45:15] Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/local/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:202:6388)
    at process.emit (node:events:531:35)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service init-mysql: stopping
s6-rc: info: service init-mosquitto: stopping
s6-rc: info: service code-server: stopping
s6-rc: info: service init-mysql successfully stopped
s6-rc: info: service init-mosquitto successfully stopped
a socket was left hanging
[09:45:56] INFO: Service code-server exited with code 0 (by signal 0)
s6-rc: info: service code-server successfully stopped
s6-rc: info: service init-user: stopping
s6-rc: info: service init-code-server: stopping
s6-rc: info: service init-user successfully stopped
s6-rc: info: service init-code-server successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.17.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.10.1
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[19:32:17] INFO: Configuring timezone (Asia/Manila)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
[19:32:17] INFO: Starting code-server...
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2024-10-05T11:32:18.119Z] info  Wrote default config file to /root/.config/code-server/config.yaml
[2024-10-05T11:32:18.447Z] info  code-server 4.93.1 69df01185ce2f80e99c9e4f8c8de1907cc7a9bc5
[2024-10-05T11:32:18.449Z] info  Using user-data-dir /data/vscode
[2024-10-05T11:32:18.465Z] info  Using config file /root/.config/code-server/config.yaml
[2024-10-05T11:32:18.465Z] info  HTTP server listening on http://0.0.0.0:1337/
[2024-10-05T11:32:18.465Z] info    - Authentication is disabled
[2024-10-05T11:32:18.465Z] info    - Not serving HTTPS
[2024-10-05T11:32:18.465Z] info  Session server listening on /data/vscode/code-server-ipc.sock
[19:32:59] 




[19:33:00] Extension host agent started.
[19:33:00] Started initializing default profile extensions in extensions installation folder. file:///data/vscode/extensions
[19:33:00] Completed initializing default profile extensions in extensions installation folder. file:///data/vscode/extensions
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda_bg.wasm
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda.js
[19:33:06] [172.30.32.2][eb1702bb][ManagementConnection] New connection established.
[19:33:06] [172.30.32.2][cdb8a303][ExtensionHostConnection] New connection established.
[19:33:07] [172.30.32.2][cdb8a303][ExtensionHostConnection] <576> Launched Extension Host Process.
[19:33:56] [172.30.32.2][eb1702bb][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda_bg.wasm
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda.js
[19:34:15] [172.30.32.2][a8f95243][ManagementConnection] New connection established.
[19:34:16] [172.30.32.2][54d6b09d][ExtensionHostConnection] New connection established.
[19:34:16] [172.30.32.2][54d6b09d][ExtensionHostConnection] <849> Launched Extension Host Process.
[19:34:22] [172.30.32.2][a8f95243][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.`

**Comment by chriselera** [comment]
Closing issue.
