### ISSUE TITLE
Missing NLS 

### ISSUE THREAD

**Issue by cskiwi** [hassio-addons/addon-vscode#906]
# Problem/Motivation

I just updated to the latest Home Assistant version ( 2024.12.0) and had to change some config, however the the addon isn't loading

## Expected behavior

To show something

## Actual behavior

A black screen.

The console shows:
```
Uncaught SyntaxError: Unexpected identifier 'Use' (at nls.messages.js:19:30745)Understand this errorAI
nls.ts:99 Uncaught Error: !!! NLS MISSING: 1703 !!!
    at vht (nls.ts:99:9)
    at h (nls.ts:83:18)
    at scanner.ts:99:44
```

**Comment by cskiwi** [comment]
Still not working
